const REQ_QURAN_LIST = "REQ_QURAN_LIST";
const REQ_QURAN_LIST_SUCCESS = "REQ_QURAN_LIST_SUCCESS";
const REQ_QURAN_LIST_FAILURE = "REQ_QURAN_LIST_FAILURE";

const REQ_QURAN_DETAIL = "REQ_QURAN_DETAIL";
const REQ_QURAN_DETAIL_SUCCESS = "REQ_QURAN_DETAIL_SUCCESS";
const REQ_QURAN_DETAIL_FAILURE = "REQ_QURAN_DETAIL_FAILURE";

const REQ_PRAYER = "REQ_PRAYER_TIME";
const REQ_PRAYER_SUCCESS = "REQ_PRAYER_TIME_SUCCESS";
const REQ_PRAYER_FAILURE = "REQ_PRAYER_TIME_FAILURE";

const SET_THEME_LIGHT = "REQ_THEME_LIGHT";
const SET_THEME_DARK = "REQ_THEME_DARK";
export {
  REQ_QURAN_LIST,
  REQ_QURAN_LIST_SUCCESS,
  REQ_QURAN_LIST_FAILURE,
  REQ_QURAN_DETAIL,
  REQ_QURAN_DETAIL_SUCCESS,
  REQ_QURAN_DETAIL_FAILURE,
  REQ_PRAYER,
  REQ_PRAYER_SUCCESS,
  REQ_PRAYER_FAILURE,
  SET_THEME_LIGHT,
  SET_THEME_DARK,
};
